# Generated by Django 5.0.7 on 2024-07-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cooperative", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                ("id", models.SmallIntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("loan_status", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="")),
                ("password", models.CharField(max_length=255)),
                (
                    "cooperative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cooperative.cooperative",
                    ),
                ),
            ],
        ),
    ]
