# Generated by Django 5.0.7 on 2024-07-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cooperative", "0001_initial"),
        ("farmer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.SmallIntegerField(primary_key=True, serialize=False)),
                ("transaction_type", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("amount", models.SmallIntegerField()),
                ("description", models.TextField()),
                ("total", models.SmallIntegerField()),
                (
                    "cooperative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cooperative.cooperative",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmer.farmer"
                    ),
                ),
            ],
        ),
    ]
